services:
  api:
    build:
      context: ../api
    container_name: books-api
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 4000
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booksdb
    depends_on:
      - db
    networks:
      - books-network

  front:
    build:
      context: ../front
    container_name: books-front
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - books-network

  db:
    image: postgres:15
    container_name: books-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booksdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - books-network

volumes:
  postgres-data:

networks:
  books-network:
